# File Type Configuration

[file_type_multipliers]
# Programming Languages
python3 = 1.4
typescript-react = 1.3
typescript = 1.2
javascript = 1.2
rust = 1.2
bash = 1.2
zsh = 1.2
fish = 1.2
ruby = 1.2
perl = 1.2
php = 1.2
lua = 1.2
julia = 1.2
r = 1.2
node = 1.2
deno = 1.2
go = 1.2
java = 1.2
kotlin = 1.2
scala = 1.2
swift = 1.2
cpp = 1.2
c = 1.2
csharp = 1.2
fsharp = 1.2

# Shell and scripting
sh = 1.2
ksh = 1.2
dash = 1.2
tcl = 1.2
awk = 1.1
sed = 1.1

# Web technologies
html = 1.1
css = 1.1
scss = 1.1
less = 1.1
vue = 1.2
svelte = 1.2

# Configuration and data
json = 1.3
yaml = 1.3
toml = 1.3
ini = 1.2
sql = 1.3

[mime_overrides]
# Web Development files
tsx = "typescript-react"
jsx = "javascript-react"
ts = "typescript"
js = "javascript"
mjs = "javascript"
cjs = "javascript"
vue = "vue"
svelte = "svelte"
html = "html"
htm = "html"
css = "css"
scss = "scss"
sass = "scss"
less = "less"

# Programming Languages
rs = "rust"
py = "python3"
rb = "ruby"
php = "php"
go = "go"
java = "java"
scala = "scala"
kt = "kotlin"
swift = "swift"
c = "c"
cpp = "cpp"
h = "c"
hpp = "cpp"
cs = "csharp"
fs = "fsharp"
pl = "perl"
pm = "perl"
r = "r"
lua = "lua"

# Shell and Script files
sh = "bash"
bash = "bash"
zsh = "zsh"
fish = "fish"
ksh = "ksh"
dash = "dash"
tcl = "tcl"
awk = "awk"
sed = "sed"

# Configuration files
json = "json"
yaml = "yaml"
yml = "yaml"
toml = "toml"
ini = "ini"

[known_dotfiles]
patterns = [
    ".gitignore",
    ".env",
    ".npmrc",
    ".yarnrc",
    ".bashrc",
    ".zshrc",
    ".vimrc",
    ".editorconfig"
]

[binary_signatures]
elf = [0x7F, 0x45, 0x4C, 0x46]  # ELF
dos_mz = [0x4D, 0x5A]  # DOS MZ
macho_32 = [0xFE, 0xED, 0xFA, 0xCE]  # Mach-O 32-bit
macho_64 = [0xFE, 0xED, 0xFA, 0xCF]  # Mach-O 64-bit
macho_universal = [0xCA, 0xFE, 0xBA, 0xBE]  # Mach-O Universal
coff = [0x7F, 0x43, 0x4F, 0x46]  # COFF

[text_detection]
printable_ratio_threshold = 0.7  # Minimum ratio of printable characters for text files
sample_size = 512  # Number of bytes to check for text/binary detection
